### ISSUE TITLE
Crashing Servers With Anvil

### ISSUE THREAD

**Issue by Nrmly** [Globox1997/tiered#107]
### Minecraft Version

Other (specify below)

### Mod Loader Version

1.20.1

### Mod Version

1.20.1

### Describe the Issue

I have a modpack and this mod is inside of it. When I or any of my friends open an anvil it instantly crashes the server and kicks everyone out. It's super annoying and it would be great if we could upgrade our items. Please try to fix this game-breaking issue as soon as possible.

### latest.log

[latest.log](https://github.com/Globox1997/tiered/files/14627594/latest.log)

### Do you use any other mods except the required ones?

Yes, I'm using the Better Adventures Modpack

**Comment by Blutaar23** [comment]
Same here. Server and client on singleplayer crashes when clicking the reforge button in anvils GUI.

Really unfortunate

**Comment by Globox1997** [comment]
The latest log does not include any crash. 
I need the server log if the server crashes

**Comment by davr** [comment]
```
BHNAJYZZW82[20:04:02] [Render thread/WARN]: GUI did not draw the dark background layer behind itself, this may result in display issues: fuzs.easyanvils.client.gui.screens.inventory.ModAnvilScreen
[20:04:04] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoClassDefFoundError: net/libz/network/LibzServerPacket
	at draylar.tiered.network.TieredServerPacket.lambda$init$2(TieredServerPacket.java:43) ~[tiered-1.3.0.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:782) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:6318) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:758) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:139) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:743) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.lang.ClassNotFoundException: net.libz.network.LibzServerPacket
	at jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source) ~[?:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.7.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	... 14 more
[20:04:04] [Render thread/WARN]: GUI did not draw the dark background layer behind itself, this may result in display issues: draylar.tiered.reforge.ReforgeScreen
[20:04:04] [Server thread/ERROR]: This crash report has been saved to: 
[20:04:04] [Server thread/INFO]: Stopping server
[20:04:04] [Server thread/INFO]: Saving players
[20:04:04] [Server thread/INFO]: davr lost connection: Disconnected
[20:04:04] [Server thread/INFO]: davr left the game
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 2024-03-27 20:04:04
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: net/libz/network/LibzServerPacket
	at draylar.tiered.network.TieredServerPacket.lambda$init$2(TieredServerPacket.java:43)
	at net.minecraft.class_3738.run(class_3738.java:18)
	at net.minecraft.class_1255.method_18859(class_1255.java:156)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:782)
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164)
	at net.minecraft.class_1255.method_16075(class_1255.java:130)
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:6318)
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:758)
	at net.minecraft.class_1255.method_18857(class_1255.java:139)
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:743)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: net.libz.network.LibzServerPacket
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 14 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.10, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 4821176016 bytes (4597 MiB) / 8589934592 bytes (8192 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 28
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-14700K
	Identifier: Intel64 Family 6 Model 183 Stepping 1
	Microarchitecture: unknown
	Frequency (GHz): 3.42
	Number of physical packages: 1
	Number of physical CPUs: 20
	Number of logical CPUs: 28
	Graphics card #0 name: NVIDIA GeForce RTX 4080 SUPER
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2702
	Graphics card #0 versionInfo: DriverVersion=31.0.15.5131
	Graphics card #1 name: Virtual Desktop Monitor
	Graphics card #1 vendor: Virtual Desktop, Inc.
	Graphics card #1 VRAM (MB): 0.00
	Graphics card #1 deviceId: unknown
	Graphics card #1 versionInfo: DriverVersion=10.54.50.446
	Memory slot #0 capacity (MB): 24576.00
	Memory slot #0 clockSpeed (GHz): 7.20
	Memory slot #0 type: Unknown
	Memory slot #1 capacity (MB): 24576.00
	Memory slot #1 clockSpeed (GHz): 7.20
	Memory slot #1 type: Unknown
	Virtual memory max (MB): 51986.38
	Virtual memory used (MB): 26566.26
	Swap memory total (MB): 3072.00
	Swap memory used (MB): 0.00
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms8192m -Xmx8192m
	Fabric Mods: 
		advancementplaques: Advancement Plaques 1.4.11
		adventurez: AdventureZ 1.4.18
		ambientsounds: AmbientSounds 5.2.20
		amplified_nether: Amplified Nether 1.2.2
		appleskin: AppleSkin 2.5.0+mc1.20
			cloth-config: Cloth Config v11 11.0.99
				cloth-basic-math: cloth-basic-math 0.6.1
		auditory: Auditory 0.0.6-1.20.1
		autotag-convention: AutoTag Convention 2.0.2+1.20
			autotag: AutoTag 2.0.2+1.20
		bedspreads: Bedspreads 6.2.0+1.20.1
		betteradvancements: Better Advancements 0.3.2.161
		betterdungeons: YUNG's Better Dungeons 1.20-Fabric-4.0.3
			org_reflections_reflections: reflections 0.10.2
		bettermineshafts: YUNG's Better Mineshafts 1.20-Fabric-4.0.4
		betterstrongholds: YUNG's Better Strongholds 1.20-Fabric-4.0.3
		betterthirdperson: Better Third Person 1.9.0
		bobby: Bobby 5.0.1
			com_typesafe_config: config 1.4.2
			io_leangen_geantyref_geantyref: geantyref 1.3.13
			org_spongepowered_configurate-core: configurate-core 4.1.2
			org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		c2me: Concurrent Chunk Management Engine 0.2.0+alpha.11.5
			c2me-base: Concurrent Chunk Management Engine (Base) 0.2.0+alpha.11.5
			c2me-client-uncapvd: Concurrent Chunk Management Engine (Client/Uncap View Distance) 0.2.0+alpha.11.5
			c2me-fixes-chunkio-threading-issues: Concurrent Chunk Management Engine (Fixes/Chunk IO/Threading Issues) 0.2.0+alpha.11.5
			c2me-fixes-general-threading-issues: Concurrent Chunk Management Engine (Fixes/General/Threading Issues) 0.2.0+alpha.11.5
			c2me-fixes-worldgen-threading-issues: Concurrent Chunk Management Engine (Fixes/WorldGen/Threading Issues) 0.2.0+alpha.11.5
			c2me-fixes-worldgen-vanilla-bugs: Concurrent Chunk Management Engine (Fixes/WorldGen/Vanilla Bugs) 0.2.0+alpha.11.5
			c2me-notickvd: Concurrent Chunk Management Engine (No Tick View Distance) 0.2.0+alpha.11.5
			c2me-opts-allocs: Concurrent Chunk Management Engine (Optimizations/Memory Allocations) 0.2.0+alpha.11.5
			c2me-opts-chunk-access: Concurrent Chunk Management Engine (Optimizations/Chunk Access) 0.2.0+alpha.11.5
			c2me-opts-chunkio: Concurrent Chunk Management Engine (Optimizations/Chunk IO) 0.2.0+alpha.11.5
			c2me-opts-math: Concurrent Chunk Management Engine (Optimizations/Math) 0.2.0+alpha.11.5
			c2me-opts-scheduling: Concurrent Chunk Management Engine (Optimizations/Scheduling) 0.2.0+alpha.11.5
			c2me-opts-worldgen-general: Concurrent Chunk Management Engine (Optimizations/General WorldGen) 0.2.0+alpha.11.5
			c2me-opts-worldgen-vanilla: Concurrent Chunk Management Engine (Optimizations/Vanilla WorldGen) 0.2.0+alpha.11.5
			c2me-rewrites-chunk-serializer: Concurrent Chunk Management Engine (Rewrites/Chunk Serializer) 0.2.0+alpha.11.5
			c2me-rewrites-chunkio: Concurrent Chunk Management Engine (Rewrites/Chunk IO) 0.2.0+alpha.11.5
			c2me-server-utils: Concurrent Chunk Management Engine (Server Utils) 0.2.0+alpha.11.5
			c2me-threading-chunkio: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.11.5
			c2me-threading-lighting: Concurrent Chunk Management Engine (Threading/Lighting) 0.2.0+alpha.11.5
			c2me-threading-worldgen: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.11.5
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
			com_ibm_async_asyncutil: asyncutil 0.1.0
			net_objecthunter_exp4j: exp4j 0.4.8
			org_threadly_threadly: threadly 7.0
		cameraoverhaul: Camera Overhaul 1.4.0-fabric-universal
		camerautils: Camera Utils 1.20.1-1.0.4
		cavedust: Cave Dust 1.4.1
			kirin: Kirin UI 1.15.0
		cherishedworlds: Cherished Worlds 6.1.0+1.20.1
		comforts: Comforts 6.3.4+1.20.1
			cardinal-components-base: Cardinal Components API (base) 5.2.1
			cardinal-components-entity: Cardinal Components API (entities) 5.2.1
			spectrelib: SpectreLib 0.13.14+1.20.1
		connectiblechains: Connectible Chains 2.2.1+1.20.1
		creativecore: CreativeCore 2.10.24
			net_minecraftforge_eventbus: eventbus 6.0.3
		cupboard: cupboard 1.20.1-2.1
		dataloader: Data loader 1.1.3+1.19.4-1.20-pre5
		diagonalfences: Diagonal Fences 8.0.0
		disable_custom_worlds_advice: Disable Custom Worlds Advice 4.1
		distanthorizons: Distant Horizons 2.0.2-a-dev
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.1+e91849a877
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.21+b3afc78b77
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.10+eeb8eb3677
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.7+b3afc78b77
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.9+132c48c177
		easyanvils: Easy Anvils 8.0.0
		easymagic: Easy Magic 8.0.0
		eatinganimationid: Eating Animation 1.9.4+1.20
		enhancedvisuals: EnhancedVisuals 1.6.7
		entity_model_features: Entity Model Features 0.2.13
		entity_texture_features: Entity Texture Features 4.4.4
			org_apache_httpcomponents_httpmime: httpmime 4.5.10
		entityculling: EntityCulling-Fabric 1.6.2-mc1.20
		exposure: Exposure 1.4.0
		extrasounds: ExtraSounds 2.3.1+1.20.1~lonefelidae16-build.1
			advanced_runtime_resource_pack: Runtime Resource Pack 0.6.7
			soundcategories: Sound Categories 1.2.4+1.20~lonefelidae16-build.1
		fabric-api: Fabric API 0.91.0+1.20.1
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.35+4d8536c977
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.12+215bbe9677
			fabric-block-api-v1: Fabric Block API (v1) 1.0.10+92a0d36777
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.0+92a0d36777
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.40+b3afc78b77
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.1+97bb207577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.33+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.12+b3afc78b77
			fabric-commands-v0: Fabric Commands (v0) 0.2.50+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.63+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.10+57aed33f77
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.4+a1a980da77
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.18+aeb40ebe77
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.3.3+d7b148e077
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.53+8536527b77
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.22+b3afc78b77
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.62+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.39+ae9f657a77
			fabric-item-api-v1: Fabric Item API (v1) 2.1.27+b3afc78b77
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.11+d7b148e077
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.34+df3654b377
			fabric-loot-api-v2: Fabric Loot API (v2) 1.2.0+96dfa95977
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.44+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.8+d7b148e077
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.49+b3afc78b77
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.2+709a987177
			fabric-models-v0: Fabric Models (v0) 0.4.1+9386d8a777
			fabric-networking-v0: Fabric Networking (v0) 0.3.50+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.2+4ee0bc6077
			fabric-particles-v1: Fabric Particles (v1) 1.1.1+201a23a077
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.20+b3afc78b77
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.2+4df89eb277
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.0+39a511ba77
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.0+39a511ba77
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.45+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.36+92a0d36777
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.27+b3afc78b77
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.48+df3654b377
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.7+29de845d77
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.7+b3afc78b77
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.29+b3afc78b77
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.12+b3afc78b77
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.3+c81d263177
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.0+6c31357e77
		fabricloader: Fabric Loader 0.15.7
			mixinextras: MixinExtras 0.3.5
		fallingleaves: Falling Leaves 1.15.1+1.20.1
		fallingtree: FallingTree 4.3.4
		firstperson: FirstpersonModel 2.2.3
		forgeconfigapiport: Forge Config API Port 8.0.0
		herdspanic: Herds Panic 1.0.7
		iceberg: Iceberg 1.1.18
		incendium: Incendium 5.3.4
		indium: Indium 1.0.30+mc1.20.4
		inmis: Inmis 2.7.2-1.20.1
			omega-config: OmegaConfig 1.2.3-1.18.1
		inmisaddon: InmisAddon 1.0.4
		invmove: InvMove 0.8.4
		iris: Iris 1.7.0-snapshot+mc1.20.1-7edecd1
			fabric-api-base: Fabric API Base 0.4.31+1802ada577
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.37+1802ada577
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		itemborders: Item Borders 1.2.1
		jamlib: JamLib 0.6.0+1.20
		java: OpenJDK 64-Bit Server VM 17
		jei: Just Enough Items 15.3.0.4
		lazydfu: LazyDFU 0.1.3
		legendarytooltips: Legendary Tooltips 1.4.4
		libz: LibZ 1.0.1
		lithium: Lithium 0.11.2
		lootr: Lootr 0.7.29.75
		minecraft: Minecraft 1.20.1
		modmenu: Mod Menu 7.1.0
		morebannerfeatures: More Banner Features 1.2.0
		moremobvariants: More Mob Variants 1.2.2
		mousewheelie: Mouse Wheelie 1.11.1+mc1.20-pre2
			amecsapi: Amecs API 1.4.0+mc1.20-pre1
			coat: Coat 1.0.0-beta.20+mc1.20-pre1
			tweed4_annotated: tweed4_annotated 1.3.1+mc1.20-pre1
			tweed4_base: tweed4_base 1.7.1+mc1.20-pre1
			tweed4_data: tweed4_data 1.2.1+mc1.20-pre1
			tweed4_data_hjson: tweed4_data_hjson 1.1.1+mc1.20-pre1
			tweed4_tailor_coat: tweed4_tailor_coat 1.1.3+mc1.20-pre1
			tweed4_tailor_lang_json_descriptions: tweed4_tailor_lang_json_descriptions 1.1.0+mc1.20-pre1
			tweed4_tailor_screen: tweed4_tailor_screen 1.1.4+mc1.20-pre1
		notenoughanimations: NotEnoughAnimations 1.6.4
		nullscape: Nullscape 1.2.4
		presencefootsteps: Presence Footsteps 1.9.0
		prism: Prism 1.0.5
		puzzleslib: Puzzles Lib 8.0.7
		reeses-sodium-options: Reese's Sodium Options 1.7.2+mc1.20.1-build.101
		replaymod: Replay Mod 1.20.1-2.6.13
		rightclickharvest: Right Click Harvest 3.2.2+1.19.x-1.20.1-fabric
		shulkerboxtooltip: Shulker Box Tooltip 4.0.4+1.20.1
		smoothswapping: Smooth Swapping 0.9.3.1
		sodium: Sodium 0.5.8+mc1.20.1
		sodium-extra: Sodium Extra 0.5.4+mc1.20.1-build.115
			caffeineconfig: CaffeineConfig 1.3.0+1.17
			crowdin-translate: CrowdinTranslate 1.4+1.19.3
		soulfired: Soul fire'd 3.2.0.0
		sound_physics_remastered: Sound Physics Remastered 1.20.1-1.1.1
		structory: Structory 1.3.4
		tectonic: Tectonic 2.2
		tiered: Tiered 1.3.0
			reach-entity-attributes: Reach Entity Attributes 2.4.0
		tinyskeletons: Tiny Skeletons 8.0.0
		trade_cycling: Trade Cycling 1.20.1-1.0.5
		trinkets: Trinkets 3.7.1
		universalbonemeal: Universal Bone Meal 8.0.0
		vanillatweaks: VanillaTweaks 1.5.69
		visuality: Visuality 0.7.0+1.20
		wakes: Wakes 0.1.6
			blue_endless_jankson: jankson 1.2.2
		yungsapi: YUNG's API 1.20-Fabric-4.0.2
			org_javassist_javassist: javassist 3.29.2-GA
	Loaded Shaderpack: (off)
	Server Running: true
	Player Count: 1 / 8; [class_3222['davr'/127, l='ServerLevel[New World]', x=-234.10, y=63.00, z=-545.21]]
	Data Packs: vanilla, fabric, tectonic:tectonic, file/New-Desert-Temple.zip (incompatible), file/New-End-Cities.zip (incompatible), file/New-Ocean-Ruins.zip (incompatible), file/New-Ruined-Portals.zip (incompatible)
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Experimental
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Launched Version: 1.20.1
#@!@# Game crashed! Crash report saved to: #@!@# 
Process exited with code -1.
```

Got the same crash, on opening the anvil reforge tab, in singleplayer

**Comment by davr** [comment]
based on the advice here: https://github.com/orgs/FabricMC/discussions/3590 I updated the libz mod and it seems to have solved the problem

**Comment by Globox1997** [comment]
Yes update LibZ to the latest version.
