### ISSUE TITLE
Reforge does not show up on 1.18.2

### ISSUE THREAD

**Issue by Aquaeyes** [Globox1997/tiered#14]
Running Tiered-1.1.0, qsl-1.1.0-beta.19_qfapi-1.0.0-beta.22_fapi-0.56.0_mc-1.18.2, cloth-config-fabric-6.2.62.

```
[15:53:01] [Server thread/ERROR]: Error executing task on Server
java.lang.ClassCastException: class net.minecraft.class_1723 cannot be cast to class draylar.tiered.reforge.ReforgeScreenHandler (net.minecraft.class_1723 and draylar.tiered.reforge.ReforgeScreenHandler are in unnamed module of loader org.quiltmc.loader.impl.launch.knot.KnotClassLoader @3cce57c7)
	at draylar.tiered.network.TieredServerPacket.lambda$init$3(TieredServerPacket.java:52) ~[tiered-1.1.0.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:157) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:808) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:165) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:131) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:790) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:784) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:140) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:769) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:701) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by Globox1997** [comment]
Reference [https://github.com/Globox1997/tiered/issues/11](https://github.com/Globox1997/tiered/issues/11)
