### ISSUE TITLE
Reforge button not working on damaged anvils (and also other modded anvils)

### ISSUE THREAD

**Issue by FederAndInk** [Globox1997/tiered#21]
tried with only Tieredz and its dependencies:

```
java.lang.ClassCastException: class net.minecraft.class_1723 cannot be cast to class draylar.tiered.reforge.ReforgeScreenHandler (net.minecraft.class_1723 and draylar.tiered.reforge.ReforgeScreenHandler are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @1a052a00)
	at draylar.tiered.network.TieredServerPacket.lambda$init$3(TieredServerPacket.java:52) ~[tiered-1.1.1.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:157) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:808) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:165) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:131) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:790) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:784) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:116) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:768) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:701) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

Why doing a mixin? Why not just make a custom reforge station?

**Comment by Globox1997** [comment]
Which mod version do you use?

**Comment by ZUIXIIDE** [comment]
I use 1.1.3 and it's also not working in damaged anvils

**Comment by FederAndInk** [comment]
> Which mod version do you use?

Sorry haven't seen your reply, yeah, I used the latest for 1.18: 1.1.1, but it also happens on the latest of 1.19

Hope you can backport to 1.18 when fixed :heart:

**Comment by Globox1997** [comment]
Fixed with [https://github.com/Globox1997/tiered/commit/6da98e1e87c808ab06817e59a088cd081dd94fa8](https://github.com/Globox1997/tiered/commit/6da98e1e87c808ab06817e59a088cd081dd94fa8)
