### ISSUE TITLE
Server crash on opening reforge menu

### ISSUE THREAD

**Issue by vaxerski** [Globox1997/tiered#97]
### Minecraft Version

1.20.x

### Mod Loader Version

Fabric API 0.88.1

### Mod Version

1.3.1

### Describe the Issue

When you open the reforge menu, you get a server crash on the usage of non-existent method.

TieredServerPacket.java@L43:
https://github.com/Globox1997/tiered/blob/a598403944e38cf9e8ac749ed29139e748bb1e2f/src/main/java/draylar/tiered/network/TieredServerPacket.java#L42-L44

Fixed by commenting the usage of the func. Everything seems to work just fine.

### latest.log

Relevant:
```
[14:49:21] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoSuchMethodError: 'void net.libz.network.LibzServerPacket.writeS2CMousePositionPacket(net.minecraft.class_3222, int, int)'
	at draylar.tiered.network.TieredServerPacket.lambda$init$2(TieredServerPacket.java:43) ~[tiered-1.3.1.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[server-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:782) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:10318) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:758) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:742) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
```

### Do you use any other mods except the required ones?

Yeah but I doubt it has anything to do with this :P

**Comment by Globox1997** [comment]
update libz
